@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

rectangle AccountDetailsRepository
rectangle AccountDetailsService
rectangle AuthController
rectangle BasketController
rectangle BasketDto
rectangle BasketExceedsStockException
rectangle BasketItemDto
rectangle BasketRepository
rectangle BasketService
rectangle BusinessInvalidStatusChangeException
rectangle BusinessOrderController
rectangle BusinessOrderDto
rectangle BusinessOrderItemDto
rectangle BusinessOrderRepository
rectangle BusinessOrderService
rectangle BusinessOwnershipException
rectangle BusinessProductController
rectangle BusinessProductRepository
rectangle BusinessProductReturnController
rectangle BusinessProductReturnDto
rectangle BusinessProductReturnRepository
rectangle BusinessProductReturnService
rectangle BusinessProductService
rectangle BusinessRegisterDto
rectangle BusinessWarrantyClaimController
rectangle BusinessWarrantyClaimDto
rectangle BusinessWarrantyClaimRepository
rectangle BusinessWarrantyClaimService
rectangle BuyerProductService
rectangle BuyerProductsController
rectangle BuyerRegisterDto
rectangle CannotModifyOrderException
rectangle CategoryController
rectangle CategoryRepository
rectangle CategoryService
rectangle CreateShippingDto
rectangle CreditCardDto
rectangle FavouriteController
rectangle FavouriteRepository
rectangle FavouriteService
rectangle GudenaPaymentClient
rectangle GudenaShippingClient
rectangle IAccountDetailsRepository
rectangle IAccountDetailsService
rectangle IBasketRepository
rectangle IBasketService
rectangle IBusinessOrderRepository
rectangle IBusinessOrderService
rectangle IBusinessProductRepository
rectangle IBusinessProductReturnRepository
rectangle IBusinessProductReturnService
rectangle IBusinessProductService
rectangle IBusinessWarrantyClaimRepository
rectangle IBusinessWarrantyClaimService
rectangle IBuyerProductService
rectangle ICategoryRepository
rectangle ICategoryService
rectangle IFavouriteRepository
rectangle IFavouriteService
rectangle IOrderItemRepository
rectangle IOrderItemService
rectangle IOrderRepository
rectangle IOrderService
rectangle IPaymentRepository
rectangle IPaymentService
rectangle IProductRepository
rectangle IProductReturnRepository
rectangle IProductReturnService
rectangle IShippingRepository
rectangle IShippingService
rectangle IWarrantyClaimRepository
rectangle IWarrantyClaimService
rectangle IncancellableOrderException
rectangle LocationsShippingsDto
rectangle LoginDto
rectangle NonReturnableProductException
rectangle OrderController
rectangle OrderExceedsStockException
rectangle OrderItemDto
rectangle OrderItemRepository
rectangle OrderItemService
rectangle OrderRepository
rectangle OrderService
rectangle OrderShippingDto
rectangle OrderUpdateDto
rectangle PaymentController
rectangle PaymentDto
rectangle PaymentRepository
rectangle PaymentService
rectangle ProductAlreadyReturnedException
rectangle ProductCreateDto
rectangle ProductRepository
rectangle ProductReturnController
rectangle ProductReturnDto
rectangle ProductReturnRepository
rectangle ProductReturnService
rectangle ResourceNotFoundException
rectangle ShippingController
rectangle ShippingRepository
rectangle ShippingService
rectangle UnpaidException
rectangle UpdateBusinessProductReturnStatusDto
rectangle UpdateBusinessWarrantyClaimStatusDto
rectangle UpdateOrderStatusDto
rectangle UpdateShippingDto
rectangle UserDoesNotOwnResourceException
rectangle UsersController
rectangle WarrantyAlreadyClaimedException
rectangle WarrantyClaimController
rectangle WarrantyClaimDto
rectangle WarrantyClaimRepository
rectangle WarrantyClaimService

AccountDetailsRepository              -[#24a394,dashed]-^  IAccountDetailsRepository            
AccountDetailsService                 -[#3574f0,plain]->>  IAccountDetailsRepository            
AccountDetailsService                 -[#5fad65,dotted]->>  IAccountDetailsRepository            
AccountDetailsService                 -[#f2c55c,plain]-*  IAccountDetailsRepository            
AccountDetailsService                 -[#24a394,dashed]-^  IAccountDetailsService               
AuthController                        -[#3574f0,plain]->>  BusinessRegisterDto                  
AuthController                        -[#3574f0,plain]->>  BuyerRegisterDto                     
AuthController                        -[#3574f0,plain]->>  LoginDto                             
BasketController                      -[#3574f0,plain]->>  BasketExceedsStockException          
BasketController                      -[#3574f0,plain]->>  BasketItemDto                        
BasketController                      -[#3574f0,plain]->>  IBasketService                       
BasketController                      -[#5fad65,dotted]->>  IBasketService                       
BasketController                      -[#f2c55c,plain]-*  IBasketService                       
BasketController                      -[#3574f0,plain]->>  ResourceNotFoundException            
BasketDto                             -[#3574f0,plain]->>  BasketItemDto                        
BasketRepository                      -[#3574f0,plain]->>  BasketExceedsStockException          
BasketRepository                      -[#24a394,dashed]-^  IBasketRepository                    
BasketRepository                      -[#3574f0,plain]->>  IProductRepository                   
BasketRepository                      -[#5fad65,dotted]->>  IProductRepository                   
BasketRepository                      -[#f2c55c,plain]-*  IProductRepository                   
BasketRepository                      -[#3574f0,plain]->>  ResourceNotFoundException            
BasketService                         -[#3574f0,plain]->>  IBasketRepository                    
BasketService                         -[#f2c55c,plain]-*  IBasketRepository                    
BasketService                         -[#5fad65,dotted]->>  IBasketRepository                    
BasketService                         -[#24a394,dashed]-^  IBasketService                       
BusinessOrderController               -[#3574f0,plain]->>  BusinessInvalidStatusChangeException 
BusinessOrderController               -[#3574f0,plain]->>  BusinessOrderDto                     
BusinessOrderController               -[#3574f0,plain]->>  BusinessOwnershipException           
BusinessOrderController               -[#f2c55c,plain]-*  IBusinessOrderService                
BusinessOrderController               -[#5fad65,dotted]->>  IBusinessOrderService                
BusinessOrderController               -[#3574f0,plain]->>  IBusinessOrderService                
BusinessOrderController               -[#3574f0,plain]->>  UpdateOrderStatusDto                 
BusinessOrderDto                      -[#3574f0,plain]->>  BusinessOrderItemDto                 
BusinessOrderRepository               -[#3574f0,plain]->>  BusinessInvalidStatusChangeException 
BusinessOrderRepository               -[#3574f0,plain]->>  BusinessOrderDto                     
BusinessOrderRepository               -[#3574f0,plain]->>  BusinessOrderItemDto                 
BusinessOrderRepository               -[#3574f0,plain]->>  BusinessOwnershipException           
BusinessOrderRepository               -[#24a394,dashed]-^  IBusinessOrderRepository             
BusinessOrderService                  -[#3574f0,plain]->>  BusinessOrderDto                     
BusinessOrderService                  -[#3574f0,plain]->>  IBusinessOrderRepository             
BusinessOrderService                  -[#f2c55c,plain]-*  IBusinessOrderRepository             
BusinessOrderService                  -[#5fad65,dotted]->>  IBusinessOrderRepository             
BusinessOrderService                  -[#24a394,dashed]-^  IBusinessOrderService                
BusinessProductController             -[#3574f0,plain]->>  IBusinessProductService              
BusinessProductController             -[#5fad65,dotted]->>  IBusinessProductService              
BusinessProductController             -[#f2c55c,plain]-*  IBusinessProductService              
BusinessProductController             -[#3574f0,plain]->>  ProductCreateDto                     
BusinessProductRepository             -[#24a394,dashed]-^  IBusinessProductRepository           
BusinessProductReturnController       -[#3574f0,plain]->>  BusinessProductReturnDto             
BusinessProductReturnController       -[#3574f0,plain]->>  IBusinessProductReturnService        
BusinessProductReturnController       -[#5fad65,dotted]->>  IBusinessProductReturnService        
BusinessProductReturnController       -[#f2c55c,plain]-*  IBusinessProductReturnService        
BusinessProductReturnController       -[#3574f0,plain]->>  UpdateBusinessProductReturnStatusDto 
BusinessProductReturnRepository       -[#3574f0,plain]->>  BusinessProductReturnDto             
BusinessProductReturnRepository       -[#24a394,dashed]-^  IBusinessProductReturnRepository     
BusinessProductReturnService          -[#3574f0,plain]->>  BusinessProductReturnDto             
BusinessProductReturnService          -[#5fad65,dotted]->>  IBusinessProductReturnRepository     
BusinessProductReturnService          -[#f2c55c,plain]-*  IBusinessProductReturnRepository     
BusinessProductReturnService          -[#3574f0,plain]->>  IBusinessProductReturnRepository     
BusinessProductReturnService          -[#24a394,dashed]-^  IBusinessProductReturnService        
BusinessProductService                -[#3574f0,plain]->>  IBusinessProductRepository           
BusinessProductService                -[#5fad65,dotted]->>  IBusinessProductRepository           
BusinessProductService                -[#f2c55c,plain]-*  IBusinessProductRepository           
BusinessProductService                -[#24a394,dashed]-^  IBusinessProductService              
BusinessProductService                -[#3574f0,plain]->>  ProductCreateDto                     
BusinessWarrantyClaimController       -[#3574f0,plain]->>  BusinessInvalidStatusChangeException 
BusinessWarrantyClaimController       -[#3574f0,plain]->>  BusinessOwnershipException           
BusinessWarrantyClaimController       -[#3574f0,plain]->>  BusinessWarrantyClaimDto             
BusinessWarrantyClaimController       -[#f2c55c,plain]-*  IBusinessWarrantyClaimService        
BusinessWarrantyClaimController       -[#3574f0,plain]->>  IBusinessWarrantyClaimService        
BusinessWarrantyClaimController       -[#5fad65,dotted]->>  IBusinessWarrantyClaimService        
BusinessWarrantyClaimController       -[#3574f0,plain]->>  UpdateBusinessWarrantyClaimStatusDto 
BusinessWarrantyClaimRepository       -[#3574f0,plain]->>  BusinessInvalidStatusChangeException 
BusinessWarrantyClaimRepository       -[#3574f0,plain]->>  BusinessOwnershipException           
BusinessWarrantyClaimRepository       -[#3574f0,plain]->>  BusinessWarrantyClaimDto             
BusinessWarrantyClaimRepository       -[#24a394,dashed]-^  IBusinessWarrantyClaimRepository     
BusinessWarrantyClaimService          -[#3574f0,plain]->>  BusinessWarrantyClaimDto             
BusinessWarrantyClaimService          -[#5fad65,dotted]->>  IBusinessWarrantyClaimRepository     
BusinessWarrantyClaimService          -[#3574f0,plain]->>  IBusinessWarrantyClaimRepository     
BusinessWarrantyClaimService          -[#f2c55c,plain]-*  IBusinessWarrantyClaimRepository     
BusinessWarrantyClaimService          -[#24a394,dashed]-^  IBusinessWarrantyClaimService        
BuyerProductService                   -[#24a394,dashed]-^  IBuyerProductService                 
BuyerProductService                   -[#3574f0,plain]->>  IProductRepository                   
BuyerProductService                   -[#5fad65,dotted]->>  IProductRepository                   
BuyerProductService                   -[#f2c55c,plain]-*  IProductRepository                   
BuyerProductsController               -[#5fad65,dotted]->>  IBuyerProductService                 
BuyerProductsController               -[#f2c55c,plain]-*  IBuyerProductService                 
BuyerProductsController               -[#3574f0,plain]->>  IBuyerProductService                 
CategoryController                    -[#3574f0,plain]->>  ICategoryService                     
CategoryController                    -[#f2c55c,plain]-*  ICategoryService                     
CategoryController                    -[#5fad65,dotted]->>  ICategoryService                     
CategoryRepository                    -[#24a394,dashed]-^  ICategoryRepository                  
CategoryService                       -[#5fad65,dotted]->>  ICategoryRepository                  
CategoryService                       -[#f2c55c,plain]-*  ICategoryRepository                  
CategoryService                       -[#3574f0,plain]->>  ICategoryRepository                  
CategoryService                       -[#24a394,dashed]-^  ICategoryService                     
FavouriteController                   -[#3574f0,plain]->>  IFavouriteService                    
FavouriteController                   -[#5fad65,dotted]->>  IFavouriteService                    
FavouriteController                   -[#f2c55c,plain]-*  IFavouriteService                    
FavouriteRepository                   -[#24a394,dashed]-^  IFavouriteRepository                 
FavouriteRepository                   -[#f2c55c,plain]-*  IProductRepository                   
FavouriteRepository                   -[#5fad65,dotted]->>  IProductRepository                   
FavouriteService                      -[#5fad65,dotted]->>  IFavouriteRepository                 
FavouriteService                      -[#3574f0,plain]->>  IFavouriteRepository                 
FavouriteService                      -[#f2c55c,plain]-*  IFavouriteRepository                 
FavouriteService                      -[#24a394,dashed]-^  IFavouriteService                    
GudenaPaymentClient                   -[#3574f0,plain]->>  CreditCardDto                        
GudenaShippingClient                  -[#3574f0,plain]->>  LocationsShippingsDto                
IBusinessOrderRepository              -[#3574f0,plain]->>  BusinessOrderDto                     
IBusinessOrderService                 -[#3574f0,plain]->>  BusinessOrderDto                     
IBusinessProductReturnRepository      -[#3574f0,plain]->>  BusinessProductReturnDto             
IBusinessProductReturnService         -[#3574f0,plain]->>  BusinessProductReturnDto             
IBusinessProductService               -[#3574f0,plain]->>  ProductCreateDto                     
IBusinessWarrantyClaimRepository      -[#3574f0,plain]->>  BusinessWarrantyClaimDto             
IBusinessWarrantyClaimService         -[#3574f0,plain]->>  BusinessWarrantyClaimDto             
IOrderRepository                      -[#3574f0,plain]->>  OrderUpdateDto                       
IOrderService                         -[#3574f0,plain]->>  OrderUpdateDto                       
IProductReturnRepository              -[#3574f0,plain]->>  ProductReturnDto                     
IProductReturnService                 -[#3574f0,plain]->>  ProductReturnDto                     
IWarrantyClaimRepository              -[#3574f0,plain]->>  WarrantyClaimDto                     
IWarrantyClaimService                 -[#3574f0,plain]->>  WarrantyClaimDto                     
OrderController                       -[#3574f0,plain]->>  CannotModifyOrderException           
OrderController                       -[#3574f0,plain]->>  IOrderService                        
OrderController                       -[#5fad65,dotted]->>  IOrderService                        
OrderController                       -[#f2c55c,plain]-*  IOrderService                        
OrderController                       -[#3574f0,plain]->>  IPaymentService                      
OrderController                       -[#f2c55c,plain]-*  IPaymentService                      
OrderController                       -[#5fad65,dotted]->>  IPaymentService                      
OrderController                       -[#3574f0,plain]->>  IncancellableOrderException          
OrderController                       -[#3574f0,plain]->>  OrderExceedsStockException           
OrderController                       -[#3574f0,plain]->>  OrderUpdateDto                       
OrderController                       -[#3574f0,plain]->>  ResourceNotFoundException            
OrderController                       -[#3574f0,plain]->>  UnpaidException                      
OrderController                       -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
OrderItemRepository                   -[#24a394,dashed]-^  IOrderItemRepository                 
OrderItemService                      -[#f2c55c,plain]-*  IOrderItemRepository                 
OrderItemService                      -[#3574f0,plain]->>  IOrderItemRepository                 
OrderItemService                      -[#5fad65,dotted]->>  IOrderItemRepository                 
OrderItemService                      -[#24a394,dashed]-^  IOrderItemService                    
OrderRepository                       -[#3574f0,plain]->>  CannotModifyOrderException           
OrderRepository                       -[#f2c55c,plain]-*  IBasketRepository                    
OrderRepository                       -[#5fad65,dotted]->>  IBasketRepository                    
OrderRepository                       -[#3574f0,plain]->>  IBasketRepository                    
OrderRepository                       -[#24a394,dashed]-^  IOrderRepository                     
OrderRepository                       -[#5fad65,dotted]->>  IPaymentRepository                   
OrderRepository                       -[#f2c55c,plain]-*  IPaymentRepository                   
OrderRepository                       -[#3574f0,plain]->>  IPaymentRepository                   
OrderRepository                       -[#5fad65,dotted]->>  IProductRepository                   
OrderRepository                       -[#f2c55c,plain]-*  IProductRepository                   
OrderRepository                       -[#3574f0,plain]->>  IProductRepository                   
OrderRepository                       -[#3574f0,plain]->>  IShippingRepository                  
OrderRepository                       -[#f2c55c,plain]-*  IShippingRepository                  
OrderRepository                       -[#5fad65,dotted]->>  IShippingRepository                  
OrderRepository                       -[#3574f0,plain]->>  IncancellableOrderException          
OrderRepository                       -[#3574f0,plain]->>  OrderExceedsStockException           
OrderRepository                       -[#3574f0,plain]->>  OrderItemDto                         
OrderRepository                       -[#3574f0,plain]->>  OrderUpdateDto                       
OrderRepository                       -[#3574f0,plain]->>  ResourceNotFoundException            
OrderRepository                       -[#3574f0,plain]->>  UnpaidException                      
OrderRepository                       -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
OrderService                          -[#f2c55c,plain]-*  IOrderRepository                     
OrderService                          -[#5fad65,dotted]->>  IOrderRepository                     
OrderService                          -[#3574f0,plain]->>  IOrderRepository                     
OrderService                          -[#24a394,dashed]-^  IOrderService                        
OrderService                          -[#3574f0,plain]->>  OrderUpdateDto                       
OrderUpdateDto                        -[#3574f0,plain]->>  OrderItemDto                         
PaymentController                     -[#3574f0,plain]->>  GudenaPaymentClient                  
PaymentController                     -[#f2c55c,plain]-*  IBasketService                       
PaymentController                     -[#3574f0,plain]->>  IBasketService                       
PaymentController                     -[#5fad65,dotted]->>  IBasketService                       
PaymentController                     -[#f2c55c,plain]-*  IPaymentService                      
PaymentController                     -[#3574f0,plain]->>  IPaymentService                      
PaymentController                     -[#5fad65,dotted]->>  IPaymentService                      
PaymentController                     -[#3574f0,plain]->>  IShippingService                     
PaymentController                     -[#f2c55c,plain]-*  IShippingService                     
PaymentController                     -[#5fad65,dotted]->>  IShippingService                     
PaymentController                     -[#3574f0,plain]->>  PaymentDto                           
PaymentDto                            -[#955ae0,plain]->>  CreditCardDto                        
PaymentDto                            -[#3574f0,plain]->>  CreditCardDto                        
PaymentRepository                     -[#24a394,dashed]-^  IPaymentRepository                   
PaymentService                        -[#5fad65,dotted]->>  IPaymentRepository                   
PaymentService                        -[#f2c55c,plain]-*  IPaymentRepository                   
PaymentService                        -[#3574f0,plain]->>  IPaymentRepository                   
PaymentService                        -[#24a394,dashed]-^  IPaymentService                      
ProductRepository                     -[#24a394,dashed]-^  IProductRepository                   
ProductReturnController               -[#5fad65,dotted]->>  IProductReturnService                
ProductReturnController               -[#f2c55c,plain]-*  IProductReturnService                
ProductReturnController               -[#3574f0,plain]->>  IProductReturnService                
ProductReturnController               -[#3574f0,plain]->>  NonReturnableProductException        
ProductReturnController               -[#3574f0,plain]->>  ProductAlreadyReturnedException      
ProductReturnController               -[#3574f0,plain]->>  ProductReturnDto                     
ProductReturnController               -[#3574f0,plain]->>  ResourceNotFoundException            
ProductReturnController               -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
ProductReturnRepository               -[#24a394,dashed]-^  IProductReturnRepository             
ProductReturnRepository               -[#3574f0,plain]->>  NonReturnableProductException        
ProductReturnRepository               -[#3574f0,plain]->>  ProductAlreadyReturnedException      
ProductReturnRepository               -[#3574f0,plain]->>  ProductReturnDto                     
ProductReturnRepository               -[#3574f0,plain]->>  ResourceNotFoundException            
ProductReturnRepository               -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
ProductReturnService                  -[#5fad65,dotted]->>  IProductReturnRepository             
ProductReturnService                  -[#f2c55c,plain]-*  IProductReturnRepository             
ProductReturnService                  -[#3574f0,plain]->>  IProductReturnRepository             
ProductReturnService                  -[#24a394,dashed]-^  IProductReturnService                
ProductReturnService                  -[#3574f0,plain]->>  ProductReturnDto                     
ShippingController                    -[#3574f0,plain]->>  CreateShippingDto                    
ShippingController                    -[#3574f0,plain]->>  GudenaShippingClient                 
ShippingController                    -[#5fad65,dotted]->>  IAccountDetailsService               
ShippingController                    -[#3574f0,plain]->>  IAccountDetailsService               
ShippingController                    -[#f2c55c,plain]-*  IAccountDetailsService               
ShippingController                    -[#3574f0,plain]->>  IBasketService                       
ShippingController                    -[#f2c55c,plain]-*  IBasketService                       
ShippingController                    -[#5fad65,dotted]->>  IBasketService                       
ShippingController                    -[#5fad65,dotted]->>  IOrderItemService                    
ShippingController                    -[#f2c55c,plain]-*  IOrderItemService                    
ShippingController                    -[#3574f0,plain]->>  IShippingService                     
ShippingController                    -[#f2c55c,plain]-*  IShippingService                     
ShippingController                    -[#5fad65,dotted]->>  IShippingService                     
ShippingController                    -[#3574f0,plain]->>  UpdateShippingDto                    
ShippingRepository                    -[#24a394,dashed]-^  IShippingRepository                  
ShippingService                       -[#5fad65,dotted]->>  IShippingRepository                  
ShippingService                       -[#3574f0,plain]->>  IShippingRepository                  
ShippingService                       -[#f2c55c,plain]-*  IShippingRepository                  
ShippingService                       -[#24a394,dashed]-^  IShippingService                     
WarrantyClaimController               -[#5fad65,dotted]->>  IWarrantyClaimService                
WarrantyClaimController               -[#3574f0,plain]->>  IWarrantyClaimService                
WarrantyClaimController               -[#f2c55c,plain]-*  IWarrantyClaimService                
WarrantyClaimController               -[#3574f0,plain]->>  ResourceNotFoundException            
WarrantyClaimController               -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
WarrantyClaimController               -[#3574f0,plain]->>  WarrantyAlreadyClaimedException      
WarrantyClaimController               -[#3574f0,plain]->>  WarrantyClaimDto                     
WarrantyClaimRepository               -[#24a394,dashed]-^  IWarrantyClaimRepository             
WarrantyClaimRepository               -[#3574f0,plain]->>  ResourceNotFoundException            
WarrantyClaimRepository               -[#3574f0,plain]->>  UserDoesNotOwnResourceException      
WarrantyClaimRepository               -[#3574f0,plain]->>  WarrantyAlreadyClaimedException      
WarrantyClaimRepository               -[#3574f0,plain]->>  WarrantyClaimDto                     
WarrantyClaimService                  -[#3574f0,plain]->>  IWarrantyClaimRepository             
WarrantyClaimService                  -[#5fad65,dotted]->>  IWarrantyClaimRepository             
WarrantyClaimService                  -[#f2c55c,plain]-*  IWarrantyClaimRepository             
WarrantyClaimService                  -[#24a394,dashed]-^  IWarrantyClaimService                
WarrantyClaimService                  -[#3574f0,plain]->>  WarrantyClaimDto                     
@enduml
