name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_only:
    name: Build GudenaPortal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore GudenaPortal.sln

      - name: Build solution
        run: dotnet build GudenaPortal.sln --no-restore --configuration Release

      # Placeholder for future test execution
      # - name: Run tests
      #   run: dotnet test Tests/Tests.csproj --no-build --configuration Release --verbosity normal
